# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\55949\Desktop\Projeto_gerenciamento\backup\tela_cadastroProdutos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(638, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_satusBar = QtWidgets.QFrame(self.centralwidget)
        self.frame_satusBar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_satusBar.setStyleSheet("background-color: rgb(56, 158, 216);")
        self.frame_satusBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_satusBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_satusBar.setObjectName("frame_satusBar")
        self.button_voltar = QtWidgets.QPushButton(self.frame_satusBar)
        self.button_voltar.setGeometry(QtCore.QRect(20, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_voltar.setFont(font)
        self.button_voltar.setStyleSheet("QPushButton{\n"
"    font-size:10px;\n"
"    background-color: #AF934C;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #A7AF4C;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #D4DE66;\n"
"}")
        self.button_voltar.setObjectName("button_voltar")
        self.verticalLayout.addWidget(self.frame_satusBar)
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setStyleSheet("\n"
"background-color: #dddddd;")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_main)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_subMain = QtWidgets.QFrame(self.frame_main)
        self.frame_subMain.setMaximumSize(QtCore.QSize(400, 500))
        self.frame_subMain.setStyleSheet("background-color: rgb(56, 158, 216);\n"
"border-radius:13px")
        self.frame_subMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_subMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_subMain.setObjectName("frame_subMain")
        self.titulo = QtWidgets.QLabel(self.frame_subMain)
        self.titulo.setGeometry(QtCore.QRect(0, 30, 401, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.frame_subMain)
        self.lineEdit_nome.setGeometry(QtCore.QRect(60, 100, 280, 50))
        self.lineEdit_nome.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(49, 116, 216);\n"
"    padding: 10px;\n"
"    padding-left: 7px;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    border: 3px solid rgb(49, 116, 216);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    color: #FFFFFF;\n"
"    padding: 13px;\n"
"    border: 2px solid #00BCD4\n"
"}\n"
"")
        self.lineEdit_nome.setMaxLength(32)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.lineEdit_qtd = QtWidgets.QLineEdit(self.frame_subMain)
        self.lineEdit_qtd.setGeometry(QtCore.QRect(60, 160, 280, 50))
        self.lineEdit_qtd.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(49, 116, 216);\n"
"    padding: 10px;\n"
"    padding-left: 7px;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    border: 3px solid rgb(49, 116, 216);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #00BCD4\n"
"    \n"
"}\n"
"")
        self.lineEdit_qtd.setMaxLength(10)
        self.lineEdit_qtd.setObjectName("lineEdit_qtd")
        self.lineEdit_dtv = QtWidgets.QLineEdit(self.frame_subMain)
        self.lineEdit_dtv.setGeometry(QtCore.QRect(60, 220, 280, 50))
        self.lineEdit_dtv.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(49, 116, 216);\n"
"    padding: 10px;\n"
"    padding-left: 7px;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    border: 3px solid rgb(49, 116, 216);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #00BCD4\n"
"    \n"
"}\n"
"")
        self.lineEdit_dtv.setMaxLength(40)
        self.lineEdit_dtv.setObjectName("lineEdit_dtv")
        self.lineEdit_preco = QtWidgets.QLineEdit(self.frame_subMain)
        self.lineEdit_preco.setGeometry(QtCore.QRect(60, 280, 280, 50))
        self.lineEdit_preco.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(49, 116, 216);\n"
"    padding: 10px;\n"
"    padding-left: 7px;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    border: 3px solid rgb(49, 116, 216);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #00BCD4\n"
"    \n"
"}\n"
"")
        self.lineEdit_preco.setMaxLength(10)
        self.lineEdit_preco.setObjectName("lineEdit_preco")
        self.button_cad = QtWidgets.QPushButton(self.frame_subMain)
        self.button_cad.setGeometry(QtCore.QRect(60, 350, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_cad.setFont(font)
        self.button_cad.setStyleSheet("QPushButton{\n"
"    font-size:14px;\n"
"    background-color: #4CAF7A;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 15px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #4CAF50;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #50DC55;\n"
"}")
        self.button_cad.setObjectName("button_cad")
        self.button_canc = QtWidgets.QPushButton(self.frame_subMain)
        self.button_canc.setGeometry(QtCore.QRect(230, 350, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_canc.setFont(font)
        self.button_canc.setStyleSheet("QPushButton{\n"
"    font-size:14px;\n"
"    background-color: #AF644C;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #AF4C4C;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #D92E2E;\n"
"}")
        self.button_canc.setObjectName("button_canc")
        self.horizontalLayout.addWidget(self.frame_subMain)
        self.verticalLayout.addWidget(self.frame_main)
        self.frame_footer = QtWidgets.QFrame(self.centralwidget)
        self.frame_footer.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_footer.setStyleSheet("background-color: rgb(56, 158, 216);")
        self.frame_footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_footer.setObjectName("frame_footer")
        self.verticalLayout.addWidget(self.frame_footer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 638, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_voltar.setText(_translate("MainWindow", "Voltar"))
        self.titulo.setText(_translate("MainWindow", "Cadastro de produtos"))
        self.lineEdit_nome.setPlaceholderText(_translate("MainWindow", "Nome do produto"))
        self.lineEdit_qtd.setPlaceholderText(_translate("MainWindow", "Quantidade"))
        self.lineEdit_dtv.setPlaceholderText(_translate("MainWindow", "Data de validade"))
        self.lineEdit_preco.setPlaceholderText(_translate("MainWindow", "Preço "))
        self.button_cad.setText(_translate("MainWindow", "Cadastrar"))
        self.button_canc.setText(_translate("MainWindow", "Cancelar"))
